#!/bin/bash

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

#[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &

#export DESKTOP_SESSION=gnome-classic
#export DGMSESSION=gnome-classic
#export STARTUP="/usr/bin/gnome-session --session=gnome-classic"

export DESKTOP_SESSION=xfce4
export DGMSESSION=xfce4
export STARTUP="startxfce4 &~/.vnc/xstartup"

#export DESKTOP_SESSION=mate-session
#export DGMSESSION=mate-session
#export STARTUP="exec /usr/bin/mate-session &"

$STARTUP
